services:
  syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing
    restart: always
    hostname: oci-1-debian-1-syncthing
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "127.0.0.1:8384:8384"
      - "22000:22000/tcp"
      - "22000:22000/udp"
      - "21027:21027/udp"
    volumes:
      - ./data:/var/syncthing
      - /:/data1
    user: root